name: バグ報告
description: バグを報告してください。
title: "[バグ]: "
labels: ["バグ", "トリアージ"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        バグ報告にご協力いただきありがとうございます！
  - type: dropdown
    id: tools_version
    attributes:
      label: ツール
      description: ご利用の茅野ななみのVRChat向け支援ツールのツールを教えてください。
      options:
        - VRChat向けニコニコ動画再生支援ツール (デフォルト)
        - VRChat向け動画プレイヤー画像表示支援ツール
        - KuronekoServer VRChat Video System
        - YTQ System
        - 陣内システム(β)（非推奨）
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 何が起きましたか？
      description: また、期待していた動作についても教えてください。
      placeholder: 起きた現象を教えてください！
      value: "バグが発生しました！"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: バージョン
      description: ご利用の茅野ななみのVRChat向け支援ツールのバージョンを教えてください。
      options:
        - 2.6 on nicovrc.net (デフォルト)
        - 2.6 on nicovideo.life (デフォルト)
        - 3.0 (beta)
        - 1.0 on nicocas.net (beta)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: vrc_version
    attributes:
      label: VRChatのバージョン
      description: ご利用のバージョンを教えてください。
      options:
        - Live (デフォルト)
        - OpenBeta
        - Android
        - Meta
        - Vive
        - iOS
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: どのブラウザで問題が発生していますか？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: 関連するログ出力
      description: 関連するログ出力をコピーして貼り付けてください。自動的にコード形式でフォーマットされるため、バックティックは不要です。
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: 行動規範
      description: この問題を提出することで、[行動規範](https://nicovrc.net/privacy)に従うことに同意します。
      options:
        - label: このプロジェクトの行動規範に従うことに同意します
          required: true
